/**
 * KeepTheStyle - Utility Functions
 * Shared utilities for the application
 */

// Debounce function for optimizing real-time updates
function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

// Throttle function for performance optimization
function throttle(func, limit) {
    let inThrottle;
    return function(...args) {
        if (!inThrottle) {
            func.apply(this, args);
            inThrottle = true;
            setTimeout(() => inThrottle = false, limit);
        }
    };
}

// Format CSS value with units
function formatCSSValue(value, defaultUnit = 'px') {
    if (!value) return '';
    if (typeof value === 'number') return value + defaultUnit;
    return value;
}

// Parse CSS value to number
function parseCSSValue(value) {
    if (typeof value === 'number') return value;
    if (typeof value === 'string') {
        const match = value.match(/^([0-9.-]+)/);
        return match ? parseFloat(match[1]) : 0;
    }
    return 0;
}

function escapeHTML(value) {
    return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}

function toKebabCase(value) {
    return String(value).replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
}

function safeFilename(value, fallback = 'untitled') {
    const clean = String(value || '').trim().replace(/[<>:"/\\|?*\x00-\x1F]/g, '-').replace(/[. ]+$/g, '').slice(0, 100);
    return clean || fallback;
}

function safeDomId(value, fallback = 'element') {
    const clean = String(value || '').trim().replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
    return clean || fallback;
}

function getInteractionAnimationCSS() {
    return `
.kts-animate { animation-duration: .6s; animation-fill-mode: both; }
.kts-fade-in { animation-name: ktsFadeIn; }
.kts-fade-out { animation-name: ktsFadeOut; }
.kts-slide-up { animation-name: ktsSlideUp; }
.kts-slide-left { animation-name: ktsSlideLeft; }
.kts-zoom-in { animation-name: ktsZoomIn; }
.kts-bounce { animation-name: ktsBounce; }
.kts-shake { animation-name: ktsShake; }
.kts-pulse { animation-name: ktsPulse; }
@keyframes ktsFadeIn { from { opacity: 0; } to { opacity: 1; } }
@keyframes ktsFadeOut { from { opacity: 1; } to { opacity: 0; } }
@keyframes ktsSlideUp { from { opacity: 0; transform: translateY(28px); } to { opacity: 1; transform: none; } }
@keyframes ktsSlideLeft { from { opacity: 0; transform: translateX(28px); } to { opacity: 1; transform: none; } }
@keyframes ktsZoomIn { from { opacity: 0; transform: scale(.82); } to { opacity: 1; transform: none; } }
@keyframes ktsBounce { 0%,20%,50%,80%,100% { transform: translateY(0); } 40% { transform: translateY(-18px); } 60% { transform: translateY(-8px); } }
@keyframes ktsShake { 0%,100% { transform: translateX(0); } 20%,60% { transform: translateX(-8px); } 40%,80% { transform: translateX(8px); } }
@keyframes ktsPulse { 0%,100% { transform: scale(1); } 50% { transform: scale(1.06); } }
@media (prefers-reduced-motion: reduce) { .kts-animate { animation-duration: .01ms !important; } }`.trim();
}

function generateInteractionRuntime(elements) {
    const rules = [];
    (elements || []).forEach(source => {
        (source.interactions || []).forEach(rule => rules.push({
            sourceId: safeDomId(source.attributes?.id || source.id),
            targetId: safeDomId((elements.find(item => item.id === rule.targetId)?.attributes?.id) || rule.targetId || source.attributes?.id || source.id),
            trigger: rule.trigger || 'click', action: rule.action || 'toggle', value: String(rule.value || '')
        }));
    });
    const payload = JSON.stringify(rules).replace(/<\//g, '<\\/');
    return `// Generated by KeepTheStyle — visual interactions\n(function () {\n    'use strict';\n    const rules = ${payload};\n    const run = (rule) => {\n        const target = document.getElementById(rule.targetId);\n        if (!target && rule.action !== 'navigate') return;\n        switch (rule.action) {\n            case 'show': target.hidden = false; target.style.visibility = 'visible'; break;\n            case 'hide': target.hidden = true; break;\n            case 'toggle': target.hidden = !target.hidden; if (!target.hidden) target.style.visibility = 'visible'; break;\n            case 'text': target.textContent = rule.value; break;\n            case 'navigate': if (/^(https?:|mailto:|tel:|\/|#)/i.test(rule.value)) window.location.href = rule.value; break;\n            case 'addClass': rule.value.split(/\\s+/).filter(Boolean).forEach(name => target.classList.add(name)); break;\n            case 'removeClass': rule.value.split(/\\s+/).filter(Boolean).forEach(name => target.classList.remove(name)); break;\n            case 'animate': {\n                const name = 'kts-' + (rule.value || 'fade-in');\n                target.classList.remove('kts-animate', name);\n                void target.offsetWidth;\n                target.classList.add('kts-animate', name);\n                target.addEventListener('animationend', () => target.classList.remove('kts-animate', name), { once: true });\n                break;\n            }\n        }\n    };\n    const bind = () => rules.forEach(rule => {\n        if (rule.trigger === 'load') { run(rule); return; }\n        const source = document.getElementById(rule.sourceId);\n        if (source) source.addEventListener(rule.trigger, () => run(rule));\n    });\n    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', bind); else bind();\n})();`;
}

// Deep clone object
function deepClone(obj) {
    try {
        return JSON.parse(JSON.stringify(obj));
    } catch (e) {
        console.error('Failed to deep clone object:', e);
        return obj;
    }
}

// Show toast notification
function showToast(message, type = 'info', duration = 3000) {
    const notification = document.createElement('div');
    notification.className = `notification notification-${type}`;
    notification.textContent = message;
    notification.style.cssText = `
        position: fixed;
        bottom: 220px;
        right: 20px;
        background: ${type === 'error' ? '#FF4D4F' : type === 'success' ? '#52C41A' : '#4D6BFF'};
        color: white;
        padding: 12px 20px;
        border-radius: 4px;
        font-family: 'Inter', sans-serif;
        font-size: 14px;
        z-index: 9999;
        animation: slideIn 0.3s ease;
        box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    `;
    
    document.body.appendChild(notification);
    
    setTimeout(() => {
        notification.style.opacity = '0';
        notification.style.transition = 'opacity 0.3s ease';
        setTimeout(() => {
            document.body.removeChild(notification);
        }, 300);
    }, duration);
}

function showChoiceDialog(title, message, choices) {
    return new Promise(resolve => {
        const backdrop = document.createElement('div');
        backdrop.className = 'app-dialog-backdrop';
        const dialog = document.createElement('div');
        dialog.className = 'app-dialog';
        dialog.setAttribute('role', 'dialog');
        dialog.setAttribute('aria-modal', 'true');
        const heading = document.createElement('h2');
        heading.textContent = title;
        const body = document.createElement('p');
        body.textContent = message;
        const actions = document.createElement('div');
        actions.className = 'app-dialog-actions';
        const close = value => { backdrop.remove(); resolve(value); };
        choices.forEach(choice => {
            const button = document.createElement('button');
            button.textContent = choice.label;
            button.className = `btn ${choice.primary ? 'btn-primary' : ''}`;
            button.addEventListener('click', () => close(choice.value));
            actions.appendChild(button);
        });
        dialog.append(heading, body, actions);
        backdrop.appendChild(dialog);
        document.body.appendChild(backdrop);
        backdrop.addEventListener('mousedown', e => { if (e.target === backdrop) close(null); });
        dialog.querySelector('button')?.focus();
    });
}
